In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [42]:
df =  pd.read_csv('datasets/oil_dataset.csv')
df.head()

Mendacium     Depth      Price
0      3.359  1722.533  74.048691
1      1.348  2062.571  83.321907
2      0.418  2013.507  82.748964
3      8.193  1420.607  84.760494
4      5.210   951.957  54.588671

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Mendacium  1000 non-null   float64
 1   Depth      1000 non-null   float64
 2   Price      1000 non-null   float64
dtypes: float64(3)
memory usage: 23.6 KB


In [44]:
fig = px.scatter_3d(df,x='Depth',y='Mendacium',z='Price',size='Price',color='Mendacium',)
fig.show()

In [45]:
X = df[['Mendacium','Depth']]
y = df['Price']
scaler = StandardScaler()
x = scaler.fit_transform(X)

In [46]:
xtrain,xtest, ytrain, ytest = train_test_split(x,y, test_size=.2, random_state=0)

In [47]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [48]:
reg = DecisionTreeRegressor(max_depth=15)
reg.fit(xtrain, ytrain)
reg.score(xtest, ytest) * 100

92.26568376649205

In [49]:
reg = LinearRegression()
reg.fit(xtrain, ytrain)
reg.score(xtest, ytest) * 100

80.96689796106963

In [50]:
pf = PolynomialFeatures()
xtrain_p = pf.fit_transform(xtrain)
xtest_p  = pf.transform(xtest)
reg = LinearRegression()
reg.fit(xtrain_p, ytrain)
reg.score(xtest_p, ytest) * 100

95.09460305044911

Random Forest Regression

In [51]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
reg = RandomForestRegressor(n_estimators=10)
reg.fit(xtrain, ytrain)
reg.score(xtest, ytest) * 100

94.94945428050703

# trying another dataset

In [19]:
df = pd.read_csv('datasets/automobiles.csv',index_col=0)
df.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                122  alfa-romero       gas        std   
1          3                122  alfa-romero       gas        std   
2          1                122  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak-rpm city-mpg  highway-mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [21]:
auto_df = df[['length','width','price']].copy()

In [22]:
fig = px.scatter_3d(auto_df,x='length',y='width',z='price',size='price',color='length',)
fig.show()

In [28]:
X = auto_df[['length','width']]
y = auto_df['price']
scaler = StandardScaler()
x = scaler.fit_transform(X)
xtrain,xtest, ytrain, ytest = train_test_split(x,y, test_size=.2, random_state=0)
reg = DecisionTreeRegressor()
reg.fit(xtrain, ytrain)
reg.score(xtest, ytest) * 100

59.08361747650061

In [29]:
reg = RandomForestRegressor(n_estimators=50)
reg.fit(xtrain, ytrain)
reg.score(xtest, ytest) * 100

77.52600752912909

# last dataset for regression

In [57]:
df = pd.read_csv('datasets/l_a_crime.csv')

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14680 entries, 0 to 14679
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MOMENT       14680 non-null  object 
 1   LOCATION     14680 non-null  object 
 2   CRIME        14680 non-null  object 
 3   VICTIM_SEX   14680 non-null  object 
 4   VICTIM_AGE   14680 non-null  float64
 5   OCCURRENCES  14680 non-null  int64  
dtypes: float64(1), int64(1), object(4)
memory usage: 688.2+ KB


In [59]:
df.head()

MOMENT LOCATION                    CRIME VICTIM_SEX  VICTIM_AGE  \
0  AFTERNOON      BAR  CRIME_AGAINST_COMMUNITY          M        21.0   
1  AFTERNOON      BAR  CRIME_AGAINST_COMMUNITY          M        34.0   
2  AFTERNOON      BAR                    FRAUD          M        29.0   
3  AFTERNOON      BAR                  ROBBERY          F        10.0   
4  AFTERNOON      BAR                  ROBBERY          F        14.0   

   OCCURRENCES  
0            1  
1            1  
2            1  
3            1  
4            1

In [60]:
df.MOMENT.unique() # dummy var needed

array(['AFTERNOON', 'MORNING', 'NIGHT'], dtype=object)

In [62]:
df.LOCATION.unique() # dummy var needed

array(['BAR', 'GARAGE', 'HEALTH_BUILDING', 'HOME', 'HOTEL', 'PARKING',
       'PRIVATE_BUILDING', 'PUBLIC_BUILDING', 'RELIGION_RELATED',
       'RESTAURANT', 'SCHOOL', 'SPORT_RELATED', 'STORE', 'STREET',
       'VEHICLE'], dtype=object)

In [64]:
df.CRIME.unique() # dummy var needed

array(['CRIME_AGAINST_COMMUNITY', 'FRAUD', 'ROBBERY', 'SEX_CRIME',
       'VANDALISM', 'VIOLENCE', 'MURDER', 'HOMICIDE'], dtype=object)

In [65]:
df.VICTIM_SEX.unique() # dummy var not required

array(['M', 'F'], dtype=object)

In [84]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [67]:
x = df[['MOMENT','LOCATION','CRIME','VICTIM_SEX','VICTIM_AGE']]
y= df['OCCURRENCES']

In [75]:
moment_enc = OneHotEncoder()
moments = moment_enc.fit_transform(df[['MOMENT']]) .toarray()
moments.astype(int)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [76]:
location_enc = OneHotEncoder()
locations = location_enc.fit_transform(df[['LOCATION']]) .toarray()
locations.astype(int)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [77]:
crime_enc = OneHotEncoder()
crimes = crime_enc.fit_transform(df[['CRIME']]) .toarray()
crimes.astype(int)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [88]:
gender_labeler = LabelEncoder() 
gender = gender_labeler.fit_transform(df[['VICTIM_SEX']])
gender

array([1, 1, 1, ..., 1, 1, 1])

In [104]:
x = np.concatenate([ 
                    df[['VICTIM_AGE']],  # dataframe
                     gender.reshape(-1,1), # reshape 2d array
                     crimes[:,:-1] ,  # removed 1 last col
                     locations[:,:-1], # removed 1 last col
                     moments[:,:-1] # removed 1 last col
                    ], axis=1)

In [106]:
xtrain,xtest, ytrain, ytest = train_test_split(x,y, test_size=.2, random_state=0)